apiVersion: v1
kind: Service
metadata:
  namespace: logging
  name: kibana
  labels:
    app: kibana
spec:
  ports:
  - port: 33000
    name: view
    nodePort: 30930
  type: NodePort
  selector:
    app: kibana
