apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  ports:
  - port: 33000
    name: view
    targetPort: 5601
    #nodePort: 30930
  type: ClusterIP
  selector:
    app: kibana
