apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-efk-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: cert-manager-webhook-duckdns-production
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - logging.innogrid.duckdns.org
    secretName: logging.innogrid-tls-secret-production
  rules:
  - host: logging.innogrid.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kibana
            port:
              number: 33000
